### ISSUE TITLE
CPU usage of DrawFBP is a little high on my Windows 7 (jre-1.8.0_133 x64), why?

### ISSUE THREAD

**Issue by pimgeek** [jpaulm/drawfbp#12]
Please see the following screenshot to get a basic idea, I could provide more info if necessary.

![image](https://user-images.githubusercontent.com/1609306/27257028-ba704832-53fa-11e7-821f-bc9328036efc.png)

I was trying to modify a simple Network Diagram, like this:
![image](https://github.com/jpaulm/javafbp/raw/master/docs/MergeandSort.png)

If the CPU usage stays high like this, I may have to maintain network connections by hand. :disappointed:

**Comment by ERnsTL** [comment]
This is also the case for me (though different OS and Java 1.8.0_181) using DrawFBP v2.14.2.

It fully saturates one CPU core.

As far as I can see using a syscall trace, it is constantly trying to read from a file descriptor and most of the time gets back ```-1 EAGAIN (Resource temporarily unavailable)```.

**Comment by jpaulm** [comment]
Not sure what "poll" means.  Also Googling this problem suggests EAGAIN only happens on a "write" - which I guess is not the case...  I found this: https://groups.google.com/forum/#!topic/linux.debian.user/yMLyIeDMsZ8 , but it involves Debian - maybe not the same problem...?   Anyway, I don't get any errors when running Eclipse debug - can you suggest how I can switch this on...?  TIA

**Comment by ERnsTL** [comment]
Regarding polling:

* [Information 1](https://en.wikipedia.org/wiki/Polling_(computer_science))
* [Busy waiting](https://en.wikipedia.org/wiki/Busy_waiting)
 * The according system call [is also called poll](https://linux.die.net/man/2/poll).

But the program does not wait for an event to happen, but tries to immediately [do a read on the file descriptor](https://linux.die.net/man/2/read) and gets an error obviously because no event has arrived yet ... and gets an error until finally an event arrives.

To sum it up, the program seems to be in a loop checking for input events or constantly redrawing the display area or something similar.

Does DrawFBP maybe have such a main/loop or event loop which could be constantly busy?

Interestingly, when running the .jar in the Java debugger, it does not behave that way... but when running the .jar regularly without enabling debugging, then it saturates a CPU core, running in a loop:

poll, read with error, read with error, read with error, .... read with success (received an event) ... poll again, read with error, read with error, read with error, ....read with success etc.

I will also check this more in-depth.

**Comment by jpaulm** [comment]
Thanks, Ernst!  I suspect this involves Java Swing's event-handling.  I use <code>invokeLater</code> for some of the focus stuff and I have quite a lot of Listeners looking out for various events.   There is no main loop...   There may also be a conflict between responsiveness and CPU usage...  This may be relevant: https://docs.oracle.com/javase/tutorial/uiswing/concurrency/ .   I haven't had a lot of time yet to dig into it, but I'll do some experimenting when I get a chance, to see if I can bring down the CPU without impacting responsiveness - maybe it's something simple!  Cheers

**Comment by jpaulm** [comment]
I feel pretty sure this problem involves redrawing "dirty" areas - repaint() seems to be creating a "dirty" area, which immediately triggers another repaint(), resulting in a tight loop.  So, yes, I am looping, but not intentionally!  It would be a great help if someone - @ERnsTL or @pimgeek or anyone... - could suggest a way to find the dirty area or areas...  Meanwhile, I will keep digging!

**Comment by jpaulm** [comment]
I think I have fixed this in v2.15.1.  The VisualVM profiler reports CPU usage dropping from 25% to around 5%.

@ERnsTL or @pimgeek, I would appreciate it if you could so some testing...  

@bobcorrick, could you do your regression testing?  Thanks a million to all of you!

**Comment by jpaulm** [comment]
Thanks so much!  So there is an improvement, but we're probably still getting dirty areas. .   Any idea how I can find them?  Is there a tool that can walk the tree of components?  Or maybe I don't understand how dirty area get created...?  Thanks in advance!

**Comment by bobcorrick** [comment]
Hi Paul,
I'll be able to find time for this over the next few days: family matters are keeping us busy (grandchildren).
Glad to see that you are still maintaining DrawFBP. I've had a break from technical work this year, so I now need to set up a laptop to get back into it for the regression testing.
All the best to you and yours,
Bob.

On 29 Aug 2018, at 03:00, Paul Morrison <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I have fixed this in v2.15.1. The VisualVM profiler reports CPU usage dropping from 25% to around 5%.

@ERnsTL<https://github.com/ERnsTL> or @pimgeek<https://github.com/pimgeek>, I would appreciate it if you could so some testing...

@bobcorrick<https://github.com/bobcorrick>, could you do your regression testing? Thanks a million to all of you!

**Comment by bobcorrick** [comment]
Hi again Paul,
I now have Java set up on a Win 10 laptop, but cannot see the latest DrawFBP via the maven.org<http://maven.org> link - only the 2.14 one.
I was expecting to see v 2.15.2 according to the GitHub remarks,
Kind regards, Bob.

On 2 Sep 2018, at 09:39, Bob <bobcorrick@outlook.com<mailto:bobcorrick@outlook.com>> wrote:

Hi Paul,
I'll be able to find time for this over the next few days: family matters are keeping us busy (grandchildren).
Glad to see that you are still maintaining DrawFBP. I've had a break from technical work this year, so I now need to set up a laptop to get back into it for the regression testing.
All the best to you and yours,
Bob.

On 29 Aug 2018, at 03:00, Paul Morrison <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I have fixed this in v2.15.1. The VisualVM profiler reports CPU usage dropping from 25% to around 5%.

@ERnsTL<https://github.com/ERnsTL> or @pimgeek<https://github.com/pimgeek>, I would appreciate it if you could so some testing...

@bobcorrick<https://github.com/bobcorrick>, could you do your regression testing? Thanks a million to all of you!

**Comment by jpaulm** [comment]
Sorry about the confusion!  I had some stuff from 2.15.0 still on Github - I didn't realize that some assets would get left even after I deleted the release!

v2.14.2 is the last (fairly) good one, but it has this CPU usage problem... v2.15.1 tried to solve it, and improved it a bit, but still no luck!  I am zeroing in on the problem, but haven't quite solved it, so v2.15.1 is only Pre-release!  Hope to get a solution in the next few days!  Fingers crossed!

**Comment by ERnsTL** [comment]
Just tested the new 2.15.2 - CPU usage is all practically zero when no diagram loaded, when minimized, with normal window size, when network diagram opened.

This issue looks very fixed to me. Thanks for hunting this down, Paul!

**Comment by bobcorrick** [comment]
Hi Paul,

I just had a short test session, late in the day - now 22:45 local time.

REPORT
Regression test using Windows 10 laptop, DrawFBP 2.15.2 - basic menu and drawing operations ok. There were a couple of observations:
File > Display Properties did not show a property list
File > Change Fonts- Text for the version number does not change when font or size is changed.

I did not exercise complex diagram creation yet, as I did not find the JavaFBP jar file: could you help me with that, please?

More soon, and kind regards to you,
All the best, Bob.

On 8 Sep 2018, at 22:03, ERnsTL <notifications@github.com<mailto:notifications@github.com>> wrote:


Just tested the new 2.15.2 - CPU usage is all practically zero when no diagram loaded, when minimized, with normal window size, when network diagram opened.

This issue looks very fixed to me. Thanks for hunting this down, Paul!

**Comment by ERnsTL** [comment]
Greetings Bob, If you are looking for the released pre-compiled DrawFBP .jar file:

1. This is a release artifact and can be found starting at [the repository web page](https://github.com/jpaulm/drawfbp/).
2. above the horizontal colored  bar there is "123 commits ... 1 branch ... 51 releases ... 2 contributors " -- click on "releases".
3. In the releases list, the v2.15.2 should already be the top entry.
4. In that entry, there is a list of attachments - the source code in zip and tarred form ... and the pre-compiled DrawFBP .jar file.

**Comment by jpaulm** [comment]
Many thanks, @ERnsTL, that's great news!  I'll mark this issue (#12) closed.  Thanks again!

**Comment by jpaulm** [comment]
Many thanks, @ERnsTL, that's great news!  I'll mark issue #closed.  Thanks again!

**Comment by jpaulm** [comment]
@bobcorrick , thanks for the testing!  @ernstl's comment about finding the JavaFBP jar file is correct, but applies to the JavaFBP repository, and the latest release is v4.1.0, so the jar file can be found at https://github.com/jpaulm/javafbp/releases/tag/v4.1.0   .

Your comment about not seeing the properties is an odd one - I can't seem to duplicate it!  I'll look and see if there are any null tests in that path..., but any additional info you can provide would be great!

**Comment by jpaulm** [comment]
By the way, @ERnsTL , you were right!  It was effectively a loop:  I was issuing a repaint inside a paintComponent method!  I didn't realize it, but that resulted in a tight loop!  Best regards, P.
